name: API Docker CI

on:
  push:
    branches: ['main', 'develop']
    paths:
      - 'apps/api/**'
      - '.github/workflows/ci-api.yml'
      - 'package*.json'
  pull_request:
    branches: ['main', 'develop']
    paths:
      - 'apps/api/**'
      - '.github/workflows/ci-api.yml'
      - 'package*.json'

jobs:
  build-api-docker:
    name: Validar build del API en Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Build imagen Docker del API
        run: docker build -t recio-api:latest -f ./apps/api/Dockerfile .

      - name: Verificar que la imagen se construyo
        run: docker image ls recio-api:latest
