name: Deploy Storefront to GitHub Pages

on:
  push:
    branches: ['main'] # Solo se despliega lo que llega a main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Web Store
        # Usamos el filtro de Turbo para compilar SOLO el storefront
        run: npx turbo build --filter=web-store

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # La carpeta de salida de Next.js en un monorepo
          path: './apps/web-store/out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
